apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: vaultwarden
  ports:
    - port: 80          # port interne du service (et du pod)
      targetPort: 80    # port sur lequel le pod écoute
      nodePort: 31082